//! GENERATED by apps/desktop/tools/gen-text-metrics.mjs — do not edit.
//! Regenerate with `pnpm gen:text-metrics` after bumping circuit-to-svg.
//!
//! The viewer sizes net-label flags from its own per-glyph table
//! (arialTextMetrics, 27px em) and this exact formula; the layout reserves
//! the same space so flags never overlap what the checker can't see.

/// Per-character advance width in em units.
static CHAR_WIDTHS: &[(char, f64)] = &[
    ('0', 0.481481),
    ('1', 0.481481),
    ('2', 0.481481),
    ('3', 0.481481),
    ('4', 0.481481),
    ('5', 0.481481),
    ('6', 0.481481),
    ('7', 0.481481),
    ('8', 0.481481),
    ('9', 0.481481),
    (' ', 0.259259),
    ('!', 0.259259),
    ('"', 0.333333),
    ('#', 0.481481),
    ('$', 0.481481),
    ('%', 0.777778),
    ('&', 0.592593),
    ('\'', 0.185185),
    ('(', 0.296296),
    (')', 0.296296),
    ('*', 0.333333),
    ('+', 0.518519),
    (',', 0.259259),
    ('-', 0.296296),
    ('.', 0.259259),
    ('/', 0.259259),
    (':', 0.259259),
    (';', 0.259259),
    ('<', 0.518519),
    ('=', 0.518519),
    ('>', 0.518519),
    ('?', 0.481481),
    ('@', 0.888889),
    ('A', 0.592593),
    ('B', 0.592593),
    ('C', 0.62963),
    ('D', 0.62963),
    ('E', 0.592593),
    ('F', 0.555556),
    ('G', 0.703704),
    ('H', 0.62963),
    ('I', 0.259259),
    ('J', 0.444444),
    ('K', 0.592593),
    ('L', 0.481481),
    ('M', 0.740741),
    ('N', 0.62963),
    ('O', 0.703704),
    ('P', 0.592593),
    ('Q', 0.703704),
    ('R', 0.62963),
    ('S', 0.592593),
    ('T', 0.555556),
    ('U', 0.62963),
    ('V', 0.592593),
    ('W', 0.851852),
    ('X', 0.592593),
    ('Y', 0.592593),
    ('Z', 0.555556),
    ('[', 0.259259),
    ('\\', 0.259259),
    (']', 0.259259),
    ('^', 0.407407),
    ('_', 0.481481),
    ('`', 0.296296),
    ('a', 0.481481),
    ('b', 0.481481),
    ('c', 0.444444),
    ('d', 0.481481),
    ('e', 0.481481),
    ('f', 0.259259),
    ('g', 0.481481),
    ('h', 0.481481),
    ('i', 0.185185),
    ('j', 0.185185),
    ('k', 0.444444),
    ('l', 0.185185),
    ('m', 0.740741),
    ('n', 0.481481),
    ('o', 0.481481),
    ('p', 0.481481),
    ('q', 0.481481),
    ('r', 0.296296),
    ('s', 0.444444),
    ('t', 0.259259),
    ('u', 0.481481),
    ('v', 0.444444),
    ('w', 0.62963),
    ('x', 0.444444),
    ('y', 0.444444),
    ('z', 0.444444),
    ('{', 0.296296),
    ('|', 0.222222),
    ('}', 0.296296),
    ('~', 0.518519),
];

const FALLBACK_EM: f64 = 0.481481;

/// Net-label font size in schematic units (circuit-to-svg fontSizeMap).
pub(crate) const NET_LABEL_FONT_SIZE: f64 = 0.18;
/// Net-label flag body height in schematic units.
pub(crate) const NET_LABEL_HEIGHT: f64 = 0.2;

const ARROW_POINT_WIDTH_FSR: f64 = 0.3;
const END_PADDING_FSR: f64 = 0.3;
const END_PADDING_EXTRA_PER_CHARACTER_FSR: f64 = 0.06;

/// Text width in em units (sum of advances; unknown chars fall back like
/// the renderer does).
pub(crate) fn text_width_em(text: &str) -> f64 {
    text.chars()
        .map(|c| {
            CHAR_WIDTHS
                .iter()
                .find(|(k, _)| *k == c)
                .map_or(FALLBACK_EM, |(_, w)| *w)
        })
        .sum()
}

/// Total rendered length of a net-label flag in schematic units — the
/// renderer's fullWidthFsr * font size, verbatim.
pub(crate) fn net_label_len(text: &str) -> f64 {
    let full = text_width_em(text)
        + ARROW_POINT_WIDTH_FSR * 2.0
        + END_PADDING_EXTRA_PER_CHARACTER_FSR * text.chars().count() as f64
        + END_PADDING_FSR;
    full * NET_LABEL_FONT_SIZE
}
